version: '3'
    
services:
    pgadmin:
        image: dpage/pgadmin4:4.21
        container_name: pgadmin01
        environment:
            - PGADMIN_DEFAULT_EMAIL=postgres
            - PGADMIN_DEFAULT_PASSWORD=postgres
            - PGADMIN_LISTEN_PORT=5050
        depends_on:
            - db

    db:
        image: postgres:12.2
        container_name: db01
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
