version: '3'
    
services:
    nginx:
        image: nginx:1.17.10
        container_name: nginx01
        ports:
            - "80:8000"
        volumes:
            - ./knu_notice:/home/src
            - ./config/nginx/dev.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web

    web:
        build: .
        container_name: web01
        command: bash -c "
            python -m pytest -n 2"
        depends_on:
            - db
        volumes:
            - ./knu_notice:/home/src
            - /static:/static
        expose:
            - "8000"

    db:
        image: postgres:12.2
        container_name: db01
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
