version: '3'
    
services:
    web:
        build: .
        container_name: web01
        command: bash -c "
            python -m pytest -n 2"
        volumes:
            - ./knu_notice:/home/src
            - /static:/static