version: '3'
    
services:
    nginx:
        image: nginx:1.17.10
        container_name: nginx01
        ports:
            - "80:8000"
        volumes:
            - ./knu_notice:/home/src
            - ./config/nginx/prod.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web

    web:
        build: .
        container_name: web01
        command: bash -c "
            python manage_prod.py collectstatic --no-input &&
            python manage_prod.py makemigrations && 
            python manage_prod.py migrate &&
            gunicorn knu_notice.prod.wsgi -b 0:8000"
        depends_on:
            - db
        volumes:
            - ./knu_notice:/home/src
            - /static:/static
        expose:
            - "8000"
        links:
            - redis

    celery:
        build: .
        container_name: celery01
        command: celery worker --app=crawling.tasks --loglevel=INFO --pidfile=
        volumes:
            - ./knu_notice:/home/src
        depends_on:
            - db
            - redis
        env_file: ./config/celery/prod.conf

    celery-beat:
        build: .
        container_name: celery-beat01
        command: celery beat --app=crawling.tasks --loglevel=INFO --pidfile=
        volumes:
            - ./knu_notice:/home/src
        depends_on:
            - db
            - redis
        env_file: ./config/celery/prod.conf

    db:
        image: postgres:12.2
        container_name: db01
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"

    redis:
        image: redis:6.0-rc4
        container_name: redis01
        ports:
            - "6379:6379"