version: '3'
    
services:
    nginx:
        image: nginx:1.17.10
        container_name: nginx01
        ports:
            - "80:80"
            - "443:443"
            - "5050:5050"
        volumes:
            - ./knu_notice:/home/knu_notice
            - ./config/nginx/:/etc/nginx/conf.d/
        depends_on:
            - web

    web:
        build: .
        container_name: web01
        command: bash -c "
            python manage_prod.py collectstatic --no-input &&
            python manage_prod.py makemigrations && 
            python manage_prod.py migrate &&
            gunicorn knu_notice.prod.wsgi -b 0:8080"
        volumes:
            - ./knu_notice:/home/knu_notice
        links:
            - redis

    celery:
        build: .
        container_name: celery01
        command: celery worker --app=crawling.tasks --pidfile=
        volumes:
            - ./knu_notice:/home/knu_notice
        depends_on:
            - redis
        env_file: ./config/celery/prod.conf

    celery-beat:
        build: .
        container_name: celery-beat01
        command: celery beat --app=crawling.tasks --pidfile=
        volumes:
            - ./knu_notice:/home/knu_notice
        depends_on:
            - redis
        env_file: ./config/celery/prod.conf

    redis:
        image: redis:6.0-rc4
        container_name: redis01
        ports:
            - "6379:6379"