data = {
    'main' : {
        'api_url' : '/notice/main',
        'name' : '강원대학교',
        'start_urls' : ['https://www.kangwon.ac.kr/www/selectBbsNttList.do?bbsNo=37'],
        'model' : 'Main',
        'id' : 'nttNo',
        'page' : 'pageIndex',
        'url_xpath' : '//*[@id="board"]/table/tbody/tr/td[3]/a',
        'titles_xpath' : '//*[@id="board"]/table/tbody/tr/td[3]/a/text()',
        'dates_xpath' : '//*[@id="board"]/table/tbody/tr/td[6]/text()',
        'authors_xpath' : '//*[@id="board"]/table/tbody/tr/td[4]/text()',
        'references_xpath' : '//*[@id="board"]/table/tbody/tr/td[2]/text()',
    },
    'cse' : {
        'api_url' : '/notice/cse',
        'name' : '컴퓨터공학과',
        'start_urls' : ['https://cse.kangwon.ac.kr/index.php?mt=page&mp=5_1_1'],
        'model' : 'Cse',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="bbsWrap"]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="bbsWrap"]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="bbsWrap"]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="bbsWrap"]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
     },
    'cba' : {
        'api_url' : '/notice/cba',
        'name' : '경영대학',
        'start_urls' : ['http://cba.kangwon.ac.kr/bbs/board.php?bo_table=sub06_1'],
        'model' : 'Cba',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'biz' : {
        'api_url' : '/notice/biz',
        'name' : '경영학과',
        'start_urls' : ['http://biz.kangwon.ac.kr/bbs/board.php?bo_table=sub06_1'],
        'model' : 'Biz',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="contens"]/div/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a',
        'titles_xpath' : '//*[@id="contens"]/div/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a/span/text()',
        'dates_xpath' : '//*[@id="contens"]/div/table/tbody/tr/td/form/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="contens"]/div/table/tbody/tr/td/form/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'account' : {
        'api_url' : '/notice/account',
        'name' : '회계학과',
        'start_urls' : ['http://account.kangwon.ac.kr/bbs/board.php?bo_table=notice'],
        'model' : 'Account',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/table/tbody/tr/td[3]/div/text()',
        'references_xpath' : None,
    },
    'economics' : {
        'api_url' : '/notice/economics',
        'name' : '경제학과',
        'start_urls' : ['http://economics.kangwon.ac.kr/bbs/board.php?bo_table=sub07_1'],
        'model' : 'Economics',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'statistics' : {
        'api_url' : '/notice/statistics',
        'name' : '정보통계학과',
        'start_urls' : ['http://statistics.kangwon.ac.kr/board/bbs/board.php?bo_table=notice_bbs'],
        'model' : 'Statistics',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="conbox"]/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a',
        'titles_xpath' : '//*[@id="conbox"]/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a/span/text()',
        'dates_xpath' : '//*[@id="conbox"]/table/tbody/tr/td/form/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="conbox"]/table/tbody/tr/td/form/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'tourism' : {
        'api_url' : '/notice/tourism',
        'name' : '관광경영학과',
        'start_urls' : ['http://tourism.kangwon.ac.kr/bbs/board.php?bo_table=notice'],
        'model' : 'Tourism',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'cll' : {
        'api_url' : '/notice/cll',
        'name' : '미래농업융합학과',
        'start_urls' : ['http://cll.kangwon.ac.kr/bbs/board.php?bo_table=sub06_1'],
        'model' : 'Cll',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'bse' : {
        'api_url' : '/notice/bse',
        'name' : '바이오시스템기계공학과',
        'start_urls' : ['http://bse.kangwon.ac.kr/bbs/board.php?bo_table=sub06_1'],
        'model' : 'Bse',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'foodtech' : {
        'api_url' : '/notice/foodtech',
        'name' : '식품생명공학과',
        'start_urls' : ['http://foodtech.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Foodtech',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'appliedplant' : {
        'api_url' : '/notice/appliedplant',
        'name' : '식물자원응용과학과',
        'start_urls' : ['http://appliedplant.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Appliedplant',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'applybio' : {
        'api_url' : '/notice/applybio',
        'name' : '응용생물학과',
        'start_urls' : ['http://applybio.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Applybio',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'horti' : {
        'api_url' : '/notice/horti',
        'name' : '원예과학과',
        'start_urls' : ['http://horti.kangwon.ac.kr/bbs/board.php?bo_table=sub5_1'],
        'model' : 'Horti',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'agecon' : {
        'api_url' : '/notice/agecon',
        'name' : '농업자원경제학과',
        'start_urls' : ['http://agecon.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Agecon',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'aed' : {
        'api_url' : '/notice/aed',
        'name' : '지역건설공학과',
        'start_urls' : ['http://aed.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Aed',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'cals' : {
        'api_url' : '/notice/cals',
        'name' : '동물생명과학대학',
        'start_urls' : ['http://cals.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Cals',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'animal' : {
        'api_url' : '/notice/animal',
        'name' : '동물산업융합학과',
        'start_urls' : ['http://animal.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Animal',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'applanimalsci' : {
        'api_url' : '/notice/applanimalsci',
        'name' : '동물응용과학과',
        'start_urls' : ['http://applanimalsci.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Applanimalsci',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
     'aniscience' : {
        'api_url' : '/notice/aniscience',
        'name' : '동물자원과학과',
        'start_urls' : ['http://aniscience.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Aniscience',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'architecture' : {
        'api_url' : '/notice/architecture',
        'name' : '건축학과',
        'start_urls' : ['http://architecture.kangwon.ac.kr/nano/www/board/list.php?bid_=comm_notice'],
        'model' : 'Architecture',
        'id' : 'idx',
        'page' : 'page',
        'url_xpath' : '/html/body/table/tbody/tr[1]/td/table/tbody/tr/td[2]/div/form/table/tbody/tr/td[2]/a',
        'titles_xpath' : '/html/body/table/tbody/tr[1]/td/table/tbody/tr/td[2]/div/form/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '/html/body/table/tbody/tr[1]/td/table/tbody/tr/td[2]/div/form/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '/html/body/table/tbody/tr[1]/td/table/tbody/tr/td[2]/div/form/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'archi' : {
        'api_url' : '/notice/archi',
        'name' : '건축공학과',
        'start_urls' : ['http://archi.kangwon.ac.kr/index.php?mt=page&mp=4_1_1'],
        'model' : 'Archi',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'civil' : {
        'api_url' : '/notice/civil',
        'name' : '토목공학과',
        'start_urls' : ['http://civil.kangwon.ac.kr/2014/index.php?mt=page&mp=6_1'],
        'model' : 'Civil',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'mechanical' : {
        'api_url' : '/notice/mechanical',
        'name' : '기계의용공학과',
        'start_urls' : ['http://mechanical.kangwon.ac.kr/index.php?mt=page&mp=5_1'],
        'model' : 'Mechanical',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'material' : {
        'api_url' : '/notice/material',
        'name' : '재료공학과',
        'start_urls' : ['http://material.kangwon.ac.kr/index.php?mt=page&mp=5_1_1'],
        'model' : 'Material',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[3]/a',
        'titles_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[3]/a/span/text()',
        'dates_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[4]/text()',
        'references_xpath' : None,
    },
    'enre' : {
        'api_url' : '/notice/enre',
        'name' : '에너지자원공학과',
        'start_urls' : ['http://www.enre.kr/index.php?mt=page&mp=5_1'],
        'model' : 'Enre',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'sme' : {
        'api_url' : '/notice/sme',
        'name' : '산업공학과',
        'start_urls' : ['http://sme.kangwon.ac.kr/index.php?mt=page&mp=5_1'],
        'model' : 'Sme',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'chemeng' : {
        'api_url' : '/notice/chemeng',
        'name' : '화학공학과',
        'start_urls' : ['http://chemeng.kangwon.ac.kr/index.php?mt=page&mp=5_1'],
        'model' : 'Chemeng',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'bioeng' : {
        'api_url' : '/notice/bioeng',
        'name' : '생물공학과',
        'start_urls' : ['http://bioeng.kangwon.ac.kr/index.php?mt=page&mp=6_1_1'],
        'model' : 'Bioeng',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'kangwonart' : {
        'api_url' : '/notice/kangwonart',
        'name' : '미술학과',
        'start_urls' : ['http://kangwonart.ac.kr/wp/?page_id=1782'],
        'model' : 'Kangwonart',
        'id' : 'uid',
        'page' : 'pageid',
        'url_xpath' : '//*[@id="kboard-list"]/div[2]/table/tbody/tr/td[2]/div/a',
        'titles_xpath' : '//*[@id="kboard-list"]/div[2]/table/tbody/tr/td[2]/div/a/text()',
        'dates_xpath' : '//*[@id="kboard-list"]/div[2]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="kboard-list"]/div[2]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'sport' : {
        'api_url' : '/notice/sport',
        'name' : '스포츠과학과',
        'start_urls' : ['http://sport.kangwon.ac.kr/board/bbs/board.php?bo_table=board_1'],
        'model' : 'Sport',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'educatio' : {
        'api_url' : '/notice/educatio',
        'name' : '사범대학',
        'start_urls' : ['http://educatio.kangwon.ac.kr/?doc=bbs/board.php&bo_table=gongi'],
        'model' : 'Educatio',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '/html/body/table/tbody/tr/td/table[2]/tbody/tr/td[3]/a',
        'titles_xpath' : '/html/body/table/tbody/tr/td/table[2]/tbody/tr/td[3]/a/span/text()',
        'dates_xpath' : '/html/body/table/tbody/tr/td/table[2]/tbody/tr/td[5]/span/text()',
        'authors_xpath' : '/html/body/table/tbody/tr/td/table[2]/tbody/tr/td[4]/span/span/span/span/text()',
        'references_xpath' : None,
    },
    'sciedu' : {
        'api_url' : '/notice/sciedu',
        'name' : '과학교육학과',
        'start_urls' : ['http://sciedu.kangwon.ac.kr/new/bbs/board.php?bo_table=notice'],
        'model' : 'Sciedu',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a',
        'titles_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a/span/text()',
        'dates_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'edu' : {
        'api_url' : '/notice/edu',
        'name' : '교육학과',
        'start_urls' : ['http://edu.kangwon.ac.kr/new/bbs/board.php?bo_table=sub04_02'],
        'model' : 'Edu',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[3]/nobr/a',
        'titles_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[3]/nobr/a/span/text()',
        'dates_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[4]/span/text()',
        'references_xpath' : None,
    },
    'mathedu' : {
        'api_url' : '/notice/mathedu',
        'name' : '수학교육과',
        'start_urls' : ['http://mathedu.kangwon.ac.kr/main.php?mt=page&mp=3_1'],
        'model' : 'Mathedu',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="oxbbsList"]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="oxbbsList"]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="oxbbsList"]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="oxbbsList"]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'history' : {
        'api_url' : '/notice/history',
        'name' : '역사교육과',
        'start_urls' : ['http://history.kangwon.ac.kr/index.php?mt=page&mp=5_1'],
        'model' : 'History',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="bbsWrap"]/form[1]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'engedu' : {
        'api_url' : '/notice/engedu',
        'name' : '영어교육과',
        'start_urls' : ['http://engedu.kangwon.ac.kr/twb_bbs/bbs_list.php?groupid=1&bcd=01_06_04_00_00'],
        'model' : 'Engedu',
        'id' : 'bn',
        'page' : 'pg',
        'url_xpath' : '//*[@id="user_board_list"]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="user_board_list"]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="user_board_list"]/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '//*[@id="user_board_list"]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'ethicsedu' : {
        'api_url' : '/notice/ethicsedu',
        'name' : '윤리교육과',
        'start_urls' : ['http://ethicsedu.kangwon.ac.kr/new/bbs/board.php?bo_table=sub04_02'],
        'model' : 'Ethicsedu',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[3]/nobr/a',
        'titles_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[3]/nobr/a/span/text()',
        'dates_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[4]/span/text()',
        'references_xpath' : None,
    },
    'ssedu' : {
        'api_url' : '/notice/ssedu',
        'name' : '일반사회교육과',
        'start_urls' : ['http://ssedu.kangwon.ac.kr/new/bbs/board.php?bo_table=sub02_01'],
        'model' : 'Ssedu',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a',
        'titles_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a/span/text()',
        'dates_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    # 'geoedu' : {
    #     'api_url' : '/notice/geoedu',
    #     'name' : '지리교육과',
    #     'start_urls' : ['http://geoedu.kangwon.ac.kr/department/notice.php?boardID=notice&b_id=&mode='],
    #     'model' : 'Geoedu',
    #     'id' : 'b_id',
    #     'page' : 'npage',
    #     'url_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a',
    #     'titles_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a/span/text()',
    #     'dates_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[4]/text()',
    #     'authors_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[3]/span/text()',
    #     'references_xpath' : None,
    # },
    'phyedu' : { 
        'api_url' : '/notice/phyedu',
        'name' : '체육교육과',
        'start_urls' : ['http://phyedu.kangwon.ac.kr/board/bbs/board.php?bo_table=board_1'],
        'model' : 'Phyedu',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'ccedu' : { 
        'api_url' : '/notice/ccedu',
        'name' : '한문교육과',
        'start_urls' : ['http://ccedu.kangwon.ac.kr/new/bbs/board.php?bo_table=gongji'],
        'model' : 'Ccedu',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a',
        'titles_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a/span/text()',
        'dates_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '/html/body/table/tbody/tr/td/form/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'social' : { 
        'api_url' : '/notice/social',
        'name' : '사회과학대학',
        'start_urls' : ['http://social.kangwon.ac.kr/bbs/zboard.php?id=notice'],
        'model' : 'Social',
        'id' : 'no',
        'page' : 'page',
        'url_xpath' : '/html/body/table[3]/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[4]/td/table/tbody/tr[3]/td/div/table[3]/tbody/tr/td[2]/a',
        'titles_xpath' : '/html/body/table[3]/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[4]/td/table/tbody/tr[3]/td/div/table[3]/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '/html/body/table[3]/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[4]/td/table/tbody/tr[3]/td/div/table[3]/tbody/tr/td[4]/span/text()',
        'authors_xpath' : '/html/body/table[3]/tbody/tr/td/table/tbody/tr/td[3]/table/tbody/tr[4]/td/table/tbody/tr[3]/td/div/table[3]/tbody/tr/td[3]/nobr/b/span/text()',
        'references_xpath' : None,
    },
    'anthro' : { 
        'api_url' : '/notice/anthro',
        'name' : '문화인류학과',
        'start_urls' : ['http://anthro.kangwon.ac.kr/bbs/zboard.php?id=bbs41'],
        'model' : 'Anthro',
        'id' : 'no',
        'page' : 'page',
        'url_xpath' : '/html/body/table[4]/tbody/tr/td[2]/table[4]/tbody/tr/td/div/table[3]/tbody/tr/td/table[1]/tbody/tr/td[2]/a',
        'titles_xpath' : '/html/body/table[4]/tbody/tr/td[2]/table[4]/tbody/tr/td/div/table[3]/tbody/tr/td/table[1]/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '/html/body/table[4]/tbody/tr/td[2]/table[4]/tbody/tr/td/div/table[3]/tbody/tr/td/table[1]/tbody/tr/td[4]/span/text()',
        'authors_xpath' : '/html/body/table[4]/tbody/tr/td[2]/table[4]/tbody/tr/td/div/table[3]/tbody/tr/td/table[1]/tbody/tr/td[3]/nobr/b/span/text()',
        'references_xpath' : None,
    },
    're1978' : { 
        'api_url' : '/notice/re1978',
        'name' : '부동산학과',
        'start_urls' : ['http://re1978.kangwon.ac.kr/bbs/zboard.php?id=bbs41'],
        'model' : 'Re1978',
        'id' : 'no',
        'page' : 'page',
        'url_xpath' : '/html/body/table[1]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr[2]/td/table[2]/tbody/tr/td/div/table[3]/tbody/tr/td/table[1]/tbody/tr/td[2]/a',
        'titles_xpath' : '/html/body/table[1]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr[2]/td/table[2]/tbody/tr/td/div/table[3]/tbody/tr/td/table[1]/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '/html/body/table[1]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr[2]/td/table[2]/tbody/tr/td/div/table[3]/tbody/tr/td/table[1]/tbody/tr/td[4]/span/text()',
        'authors_xpath' : '/html/body/table[1]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr[2]/td/table[2]/tbody/tr/td/div/table[3]/tbody/tr/td/table[1]/tbody/tr/td[3]/nobr/b/span/text()',
        'references_xpath' : None,
    },
    'sociology' : { 
        'api_url' : '/notice/sociology',
        'name' : '사회학과',
        'start_urls' : ['http://sociology.kangwon.ac.kr/bbs/zboard.php?id=notice'],
        'model' : 'Sociology',
        'id' : 'no',
        'page' : 'page',
        'url_xpath' : '/html/body/table[7]/tbody/tr/td/table[1]/tbody/tr/td[2]/table[2]/tbody/tr/td/div/table[3]/tbody/tr/td/table[1]/tbody/tr/td[2]/a',
        'titles_xpath' : '/html/body/table[7]/tbody/tr/td/table[1]/tbody/tr/td[2]/table[2]/tbody/tr/td/div/table[3]/tbody/tr/td/table[1]/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '/html/body/table[7]/tbody/tr/td/table[1]/tbody/tr/td[2]/table[2]/tbody/tr/td/div/table[3]/tbody/tr/td/table[1]/tbody/tr/td[4]/span/text()',
        'authors_xpath' : '/html/body/table[7]/tbody/tr/td/table[1]/tbody/tr/td[2]/table[2]/tbody/tr/td/div/table[3]/tbody/tr/td/table[1]/tbody/tr/td[3]/nobr/b/span/text()',
        'references_xpath' : None,
    },
    'masscom' : { 
        'api_url' : '/notice/masscom',
        'name' : '신문방송학과',
        'start_urls' : ['http://masscom.kangwon.ac.kr/bbs/board.php?bo_table=sub3_1'],
        'model' : 'Masscom',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="ctn"]/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a',
        'titles_xpath' : '//*[@id="ctn"]/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a/span/text()',
        'dates_xpath' : '//*[@id="ctn"]/table/tbody/tr/td/form/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="ctn"]/table/tbody/tr/td/form/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'politics' : { 
        'api_url' : '/notice/politics',
        'name' : '정치외교학과',
        'start_urls' : ['http://politics.kangwon.ac.kr/bbs/board.php?bo_table=sub9_3'],
        'model' : 'Politics',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="ctn"]/form/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="ctn"]/form/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="ctn"]/form/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="ctn"]/form/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'padm' : { 
        'api_url' : '/notice/padm',
        'name' : '행정학과',
        'start_urls' : ['http://padm.kangwon.ac.kr/bbs/board.php?bo_table=sub3_2'],
        'model' : 'Padm',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div[1]/ul/li/div[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div[1]/ul/li/div[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div[1]/ul/li/div[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div[1]/ul/li/div[3]/span/text()',
        'references_xpath' : None,
    },
    'psych' : { 
        'api_url' : '/notice/psych',
        'name' : '심리학과',
        'start_urls' : ['http://psych.kangwon.ac.kr/gnuboard4/bbs/board.php?bo_table=bbs41'],
        'model' : 'Psych',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '/html/body/table[2]/tbody/tr[3]/td/table/tbody/tr/td[2]/table[2]/tbody/tr/td/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a',
        'titles_xpath' : '/html/body/table[2]/tbody/tr[3]/td/table/tbody/tr/td[2]/table[2]/tbody/tr/td/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a/span/text()',
        'dates_xpath' : '/html/body/table[2]/tbody/tr[3]/td/table/tbody/tr/td[2]/table[2]/tbody/tr/td/table/tbody/tr/td/form/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '/html/body/table[2]/tbody/tr[3]/td/table/tbody/tr/td[2]/table[2]/tbody/tr/td/table/tbody/tr/td/form/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'forest' : { 
        'api_url' : '/notice/forest',
        'name' : '산림환경과학대학',
        'start_urls' : ['http://forest.kangwon.ac.kr/bbs/board.php?bo_table=sub06_1'],
        'model' : 'Forest',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'fm' : { 
        'api_url' : '/notice/fm',
        'name' : '산림경영학과',
        'start_urls' : ['http://fm.kangwon.ac.kr/bbs/board.php?bo_table=sub06_1'],
        'model' : 'Fm',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'forestry' : { 
        'api_url' : '/notice/forestry',
        'name' : '산림자원학과',
        'start_urls' : ['http://forestry.kangwon.ac.kr/bbs/board.php?bo_table=sub06_1'],
        'model' : 'Forestry',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[5]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'fep' : { 
        'api_url' : '/notice/fep',
        'name' : '산림환경보호학과',
        'start_urls' : ['http://fep.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Fep',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="contens"]/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a',
        'titles_xpath' : '//*[@id="contens"]/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a/text()',
        'dates_xpath' : '//*[@id="contens"]/table/tbody/tr/td/form/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="contens"]/table/tbody/tr/td/form/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'wood' : { 
        'api_url' : '/notice/wood',
        'name' : '산림소재공학과',
        'start_urls' : ['http://wood.kangwon.ac.kr/bbs/board.php?bo_table=sub07_1'],
        'model' : 'Wood',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'paper' : { 
        'api_url' : '/notice/paper',
        'name' : '제지공학과',
        'start_urls' : ['http://paper.kangwon.ac.kr/board/bbs/board.php?bo_table=sub03_1'],
        'model' : 'Paper',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="contents"]/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a',
        'titles_xpath' : '//*[@id="contents"]/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a/span/text()',
        'dates_xpath' : '//*[@id="contents"]/table/tbody/tr/td/form/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="contents"]/table/tbody/tr/td/form/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'lands' : { 
        'api_url' : '/notice/lands',
        'name' : '생태조경디자인학과',
        'start_urls' : ['http://lands.kangwon.ac.kr/bbs/board.php?bo_table=sub03_01'],
        'model' : 'Lands',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div[1]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div[1]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div[1]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div[1]/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'vetmed' : { 
        'api_url' : '/notice/vetmed',
        'name' : '수의과대학',
        'start_urls' : ['http://vetmed.kangwon.ac.kr/bbs/board.php?bo_table=sub07_1'],
        'model' : 'Vetmed',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="subcontent"]/div[3]/table/tbody/tr[1]/td/form/table/tbody/tr/td[2]/nobr/a',
        'titles_xpath' : '//*[@id="subcontent"]/div[3]/table/tbody/tr[1]/td/form/table/tbody/tr/td[2]/nobr/a/text()',
        'dates_xpath' : '//*[@id="subcontent"]/div[3]/table/tbody/tr[1]/td/form/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="subcontent"]/div[3]/table/tbody/tr[1]/td/form/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'pharmacy' : { 
        'api_url' : '/notice/pharmacy',
        'name' : '약학대학',
        'start_urls' : ['http://pharmacy.kangwon.ac.kr/bbs/board.php?bo_table=sub02_05'],
        'model' : 'Pharmacy',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/div/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'bmcollege' : { 
        'api_url' : '/notice/bmcollege',
        'name' : '의생명과학대학',
        'start_urls' : ['http://bmcollege.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Bmcollege',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'molscien' : { 
        'api_url' : '/notice/molscien',
        'name' : '분자생명과학과',
        'start_urls' : ['http://molscien.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Molscien',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'bio_health' : { 
        'api_url' : '/notice/bio-health',
        'name' : '생명건강공학과',
        'start_urls' : ['http://bio-health.kangwon.ac.kr/bbs/board.php?bo_table=sub04_1'],
        'model' : 'Bio_health',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'bme' : { 
        'api_url' : '/notice/bme',
        'name' : '생물의소재공학과',
        'start_urls' : ['http://bme.kangwon.ac.kr/bbs/board.php?bo_table=sub04_1'],
        'model' : 'Bme',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    }, 
    'si' : { 
        'api_url' : '/notice/si',
        'name' : '시스템면역과학과',
        'start_urls' : ['http://si.kangwon.ac.kr/bbs/board.php?bo_table=sub05_1'],
        'model' : 'Si',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'dmbt' : { 
        'api_url' : '/notice/dmbt',
        'name' : '의생명공학과',
        'start_urls' : ['http://dmbt.kangwon.ac.kr/bbs/board.php?bo_table=sub07_1'],
        'model' : 'Dmbt',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    }, 
    



    'it' : {
        'api_url' : '/notice/it',
        'name' : 'IT대학',
        'start_urls' : ['http://it.kangwon.ac.kr/index.php?mt=page&mp=4_1'],
        'model' : 'It',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="bbsWrap"]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '///*[@id="bbsWrap"]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="bbsWrap"]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="bbsWrap"]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },

}


# for i in range(1, 21):
#     data[f'testboard{i}'] = {
#         'api_url' : f'/notice/testboard{i}',
#         'name' : f'테스트학과{i}',
#     }