data = {
    'main' : {
        'api_url' : '/notice/main',
        'name' : '강원대학교',
        'start_urls' : ['https://www.kangwon.ac.kr/www/selectBbsNttList.do?bbsNo=37&&pageUnit=10'],
        'model' : 'Main',
        'id' : 'nttNo',
        'page' : 'pageIndex',
        'url_xpath' : '//*[@id="board"]/table/tbody/tr/td[3]/a',
        'titles_xpath' : '//*[@id="board"]/table/tbody/tr/td[3]/a/text()',
        'dates_xpath' : '//*[@id="board"]/table/tbody/tr/td[6]/text()',
        'authors_xpath' : '//*[@id="board"]/table/tbody/tr/td[4]/text()',
        'references_xpath' : '//*[@id="board"]/table/tbody/tr/td[2]/text()',
    },
    'cse' : {
        'api_url' : '/notice/cse',
        'name' : '컴퓨터공학과',
        'start_urls' : ['https://cse.kangwon.ac.kr/index.php?mt=page&mp=5_1_1&mm=oxbbs&oxid=9&key=&val=&subcmd=&CAT_ID=0&artpp=15'],
        'model' : 'Cse',
        'id' : 'BID',
        'page' : 'cpage',
        'url_xpath' : '//*[@id="bbsWrap"]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="bbsWrap"]/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="bbsWrap"]/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="bbsWrap"]/table/tbody/tr/td[3]/text()',
        'references_xpath' : None,
    },
    'cba' : {
        'api_url' : '/notice/cba',
        'name' : '경영대학',
        'start_urls' : ['http://cba.kangwon.ac.kr/bbs/board.php?bo_table=sub06_1'],
        'model' : 'Cba',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[2]/a/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[4]/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/div/table/tbody/tr/td[3]/span/text()',
        'references_xpath' : None,
    },
    'account' : {
        'api_url' : '/notice/account',
        'name' : '회계학과',
        'start_urls' : ['http://account.kangwon.ac.kr/bbs/board.php?bo_table=notice'],
        'model' : 'Account',
        'id' : 'wr_id',
        'page' : 'page',
        'url_xpath' : '//*[@id="fboardlist"]/table/tbody/tr/td[2]/a',
        'titles_xpath' : '//*[@id="contens"]/div/table/tbody/tr/td/form/table/tbody/tr/td[2]/nobr/a/span/text()',
        'dates_xpath' : '//*[@id="fboardlist"]/table/tbody/tr/td[4]/div/text()',
        'authors_xpath' : '//*[@id="fboardlist"]/table/tbody/tr/td[3]/div/text()',
        'references_xpath' : None,
    },
}

for i in range(1, 21):
    data[f'testboard{i}'] = {
        'api_url' : f'/notice/testboard{i}',
        'name' : f'테스트학과{i}',
    }