version: 2.1
jobs:
    build:
        machine:
            image: ubuntu-1604:202004-01
        steps:
            - checkout
            - run: docker-compose -f docker-compose.test.yml up
            - store_artifacts:
                path: ~/repo/features/fail-screenshots

workflows:
    build:
        jobs:
        # 위에서 작성한 job명칭을 입력한다.
        - build