version: 2.1
jobs:
    # build:
    #     machine:
    #         image: ubuntu-1604:202004-01
    #     steps:
    #         - checkout
    #         - run:
    #             command: |
    #                 set -e
    #                 docker-compose -f db.yml up --build -d
    #                 docker-compose -f docker-compose.prod.yml up --build -d
    #         - store_artifacts:
    #             path: ~/repo/features/fail-screenshots
    test:
        machine:
            image: ubuntu-1604:202004-01
        steps:
            - checkout
            - run:
                command: |
                    set +e
                    docker-compose -f docker-compose.test.yml up --build
            - store_artifacts:
                path: ~/repo/features/fail-screenshots

workflows:
    build:
        jobs:
        # 위에서 작성한 job명칭을 입력한다.
        # - build
        - test