version: 2.1 # CircleCI version
jobs:
  build:
    machine: ubuntu-1604:202004-01 # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose -f docker-compose.test.yml up -d
      - store_artifacts:
        path: ~/repo/features/fail-screenshots

workflows:
  build:
    jobs:
      # 위에서 작성한 job명칭을 입력한다.
      - build